name: HeroStackDrops
version: ${project.version}
author: Heroslender
api-version: 1.13
main: com.heroslender.herostackdrops.StackDrops
description: Plugin de juntar os itens dropados
website: www.heroslender.cf/plugins/HeroStackDrops
