name: HeroStackDrops
version: 1.5.2
author: Heroslender
main: com.heroslender.StackDrops

commands:
  stackdrops:
     description: Comando principal do HeroStackDrops.
     usage: Brevemente disponivel
#     usage: §c/<command> <reload>